### ISSUE TITLE
"Nearby" does not work when there are multiple animal pens of the same type.

### ISSUE THREAD

**Issue by LosaMatova** [w33zl/FS19_Stockman#2]
The "Nearby" mode does not display when there are multiple pens of the same type. It seems to "pick one" and only work for that one.

**Comment by w33zl** [comment]
Bugs and feature requests are tracked at the project page for Stockman, please follow the progress here: https://mikaelleven.myjetbrains.com/youtrack/issue/STOCKMAN-10
